SELECT
E.Source_Order_Number AS ORDER_NUM,
E.Header_ID  AS HDR_ID,
F.Line_id  AS LINE_ID ,
G.Fulfill_Line_id   AS FULFILL_ID,            
A.HOLD_INSTANCE_ID AS HLD_INST_ID,
A.ORCHESTRATION_APPLICATION_ID AS ORCH_APPL_ID,
A.OBJECT_VERSION_NUMBER AS OBJ_VER_ID,
A.HOLD_CODE_ID AS HOLD_CODE_ID,
A.APPLY_USER_ID AS APPLY_USRID,
A.APPLY_DATE AS APPLY_DT,
A.RELEASE_USER_ID AS REL_USRID,
A.RELEASE_DATE AS REL_DATE,
A.ACTIVE_FLAG AS ACTIVE_FLG,
A.PENDING_FLAG AS PENDING_FLG,
A.DELETED_FLAG AS DEL_FLG,
A.HOLD_RUNNING_TASK_FLAG AS HOLD_RUN_TSK,
A.HOLD_RELEASE_REASON_CODE AS REL_RSN,
A.TRANSACTION_ENTITY_ID1 AS TRX_ENTITY_ID,
A.TRANSACTION_ENTITY_NAME1 AS TRX_ENTT_NAME1,
A.TRANSACTION_ENTITY_NAME2 AS TRX_ENTT_NAME2,
C.HOLD_NAME    AS HOLD_NM,
C.HOLD_DESCRIPTION  AS HOLD_DESC,
B.EFFECTIVE_START_DATE     AS EFF_START_DATE ,
B.EFFECTIVE_END_DATE   AS EFF_END_DATE,
B.GENERAL_HOLD_FLAG   AS GEN_HOLD,
B.SYSTEM_FLAG    AS SYSTEM_FLG,
B.APPLY_HOLD_ROLE_ELIGIBILITY   AS APPLY_HOLD_ROLE_ELIG,
B.RELEASE_HOLD_ROLE_ELIGIBILITY AS REL_HOLD_ROLE_ELIG
      

FROM
DOO_HOLD_INSTANCES A,
DOO_HOLD_CODES_B B,
DOO_HOLD_CODES_tl C,
DOO_HEADERS_ALL E,
DOO_LINES_ALL F,
DOO_FULFILL_LINES_ALL G

WHERE A.HOLD_CODE_ID = B.HOLD_CODE_ID
AND A.HOLD_CODE_ID = C.HOLD_CODE_ID
AND C.LANGUAGE = USERENV('LANG')
AND E.Header_ID = F.Header_id
AND E.Header_ID = G.Header_id
AND G.line_id   = F.line_id
AND
  (
          (
                  A.TRANSACTION_ENTITY_NAME1   = 'DOO_ORDER_LINES_V'
              AND A.TRANSACTION_ENTITY_ID1 = F.Line_id
           )
 OR
           (
                   A.TRANSACTION_ENTITY_NAME1   = 'DOO_ORDER_HEADERS_V'
               AND A.TRANSACTION_ENTITY_ID1 = E.Header_id
            )
OR
           (
                   A.TRANSACTION_ENTITY_NAME1   = 'DOO_ORDER_FLINES_V'
               AND A.TRANSACTION_ENTITY_ID1 = G.Fulfill_Line_id
            )


)