 (SELECT
a.HEADER_ID "HDR_ID",
b.LINE_ID "LINE_ID",
c.FULFILL_LINE_ID "FULFILL_ID",
a.ORDER_NUMBER "ORDER_NUM",
a.ORDERED_DATE "ORDER_DATE",
a.TRANSACTIONAL_CURRENCY_CODE "ORDER_CURRENCY",
a.ORIG_SYS_DOCUMENT_REF "ORIG_SYS_REF",
a.CUSTOMER_PO_NUMBER "PO_NUM",
a.ORDER_TYPE_CODE "ORDER_TYPE_CODE",
a.STATUS_CODE "ORDER_STATUS",
a.OPEN_FLAG "ORDER_OPEN",
a.CANCELED_FLAG "ORDER_CANCEL",
a.CANCEL_REASON_CODE "ORDER_CANCEL_REASON",
e.PARTY_NAME "SOLD_TO_PARTY",
a.COMMENTS "ORDER_COMMENTS",
b.LINE_NUMBER "LINE_NUM",
b.STATUS_CODE "LINE_STATUS",
b.SOURCE_LINE_NUMBER "SRC_LINE_NUM",
b.SOURCE_ORDER_SYSTEM "SRC_ORDER_SYSTEM",
b.EXTENDED_AMOUNT "LINE_EXT_AMOUNT",
b.OPEN_FLAG "LINE_OPEN_FLAG",
b.CANCELED_FLAG "LINE_CANCEL_FLAG",
c.STATUS_CODE "FULFILL_STATUS",
c.SOURCE_SCHEDULE_ID "SCHEDULE_ID",
c.ORDERED_QTY "FULFILL_ORD_QTY",
c.ORDERED_UOM "FULFILL_ORD_UOM",
p.ITEM_NUMBER  "ORDERED_ITEM",
q.DESCRIPTION "ITEM_DESCRIPTION",
c.UNIT_LIST_PRICE "UNIT_LIST_PRC",
c.UNIT_SELLING_PRICE "UNIT_SELL_PRICE",
c.ON_HOLD "FULFILL_LINE_ON_HOLD",
c.FULFILL_LINE_NUMBER "FULFILL_LINE_NUM",
c.REQUEST_SHIP_DATE "REQ_SHIP_DATE",
c.SCHEDULE_ARRIVAL_DATE "SCH_ARRIVAL_DATE",
d.NAME "BU_NAME",
c.BILL_TO_CONTACT_ID "BILL_TO_CONTACT_ID",
h.ACCOUNT_NUMBER "BILL_TO_ACCT_NUM",
h.ACCOUNT_NAME "BILL_TO_ACCT_NAME",
l.ADDRESS1 "BILLTO_ADD1",
l.ADDRESS2 "BILLTO_ADD2",
l.CITY     "BILLTO_CITY",
l.STATE    "BILLTO_STATE",
l.COUNTRY  "BILLTO_COUNTRY",
l.POSTAL_CODE "BILLTO_ZIP",
l.ADDRESS1||' '||l.ADDRESS2||' '||l.CITY||' '||l.STATE||' '||l.COUNTRY||' '||l.POSTAL_CODE "BILLTO_FULLADDRESS",
c.SHIP_TO_CONTACT_ID "SHIP_TO_CONTACT_ID",
c.SHIP_TO_SITE_USE_ID "SHIP_TO_SITE_USE_ID",
g.PARTY_NAME "SOLD_TO_CONTACT",
o.ADDRESS1 "SHIPTO_ADD1",
o.ADDRESS2 "SHIPTO_ADD2",
o.CITY     "SHIPTO_CITY",
o.STATE    "SHIPTO_STATE",
o.COUNTRY  "SHIPTO_COUNTRY",
o.POSTAL_CODE "SHIPTO_ZIP",
o.ADDRESS1||' '||l.ADDRESS2||' '||l.CITY||' '||l.STATE||' '||l.COUNTRY||' '||l.POSTAL_CODE "SHIPTO_FULLADDRESS",
c.EXTENDED_AMOUNT "LINE_AMOUNT",
c.ACTUAL_SHIP_DATE "ACTUAL_SHIP_DATE",
c.SCHEDULE_SHIP_DATE "SCHEDULE_SHIP_DATE",
s.SHIPFROM_ORGCODE "SHIPFROM_ORGCODE",
s.SHIPFROM_ORGNAME "SHIPFROM_ORGNAME",
r.cat_desc "ITEM_CATEGORY",
c.EXTENDED_AMOUNT "EXTENDED_AMT"

FROM
DOO_HEADERS_ALL_V a,
DOO_LINES_ALL b,
DOO_FULFILL_LINES_ALL c,
HR_ALL_ORGANIZATION_UNITS_F_VL d,
HZ_PARTIES e,
HZ_CONTACT_POINTS f,
HZ_PARTIES g,
HZ_CUST_ACCOUNTS h,
HZ_CUST_SITE_USES_ALL i,
HZ_CUST_ACCT_SITES_ALL j,
HZ_PARTY_SITES k,
HZ_LOCATIONS l,
DOO_ORDER_ADDRESSES m,
HZ_PARTY_SITES n,
HZ_LOCATIONS o,
EGP_SYSTEM_ITEMS_B p,
EGP_SYSTEM_ITEMS_TL q,
(
SELECT
catas.INVENTORY_ITEM_ID AS inv_id,
catd.DESCRIPTION AS cat_desc
FROM EGP_CATEGORY_SET_VALID_CATS vc,
EGP_CATEGORY_SETS_B cs,
EGP_CATEGORIES_B cat,
EGP_CATEGORIES_TL catd,
EGP_ITEM_CAT_ASSIGNMENTS catas
WHERE cs.CATALOG_CODE = 'ABC_PRICING_CATALOG'
AND vc.CATEGORY_ID = cat.CATEGORY_ID
AND vc.CATEGORY_SET_ID = cs.CATEGORY_SET_ID
AND vc.CATEGORY_ID = catd.CATEGORY_ID
AND catd.LANGUAGE = 'US'
AND catas.ORGANIZATION_ID = 300000001749132
AND catas.CATEGORY_ID = vc.CATEGORY_ID
AND catas.CATEGORY_SET_ID = vc.CATEGORY_SET_ID
 )  r,
(
select
ORGANIZATION_ID "SHIPFROM_ORGID",
ORGANIZATION_CODE "SHIPFROM_ORGCODE",
ORGANIZATION_NAME "SHIPFROM_ORGNAME"
from
inv_organization_definitions_v
union
select
NULL,
NULL,
NULL
from
inv_organization_definitions_v
) s

WHERE a.HEADER_ID = b.HEADER_ID
AND a.HEADER_ID = c.HEADER_ID
AND b.LINE_ID = c.LINE_ID
AND a.org_id = d.organization_id
AND a.SOLD_TO_PARTY_ID = e.PARTY_ID
AND a.SOLD_TO_PARTY_CONTACT_POINT_ID = f.CONTACT_POINT_ID (+)
AND f.OWNER_TABLE_ID = g.PARTY_ID (+)
AND c.BILL_TO_CUSTOMER_ID = h.CUST_ACCOUNT_ID
AND c.BILL_TO_SITE_USE_ID = i.SITE_USE_ID
AND i.CUST_ACCT_SITE_ID = j.CUST_ACCT_SITE_ID
AND j.PARTY_SITE_ID = k.PARTY_SITE_ID
AND k.LOCATION_ID = l.LOCATION_ID
AND a.HEADER_ID = m.HEADER_ID
AND m.ADDRESS_USE_TYPE = 'SHIP_TO'
AND m.PARTY_SITE_ID = n.PARTY_SITE_ID
AND n.LOCATION_ID = o.LOCATION_ID
AND c.INVENTORY_ITEM_ID = p.INVENTORY_ITEM_ID
AND c.INVENTORY_ORGANIZATION_ID = p.ORGANIZATION_ID
AND p.INVENTORY_ITEM_ID = q.INVENTORY_ITEM_ID
AND p.ORGANIZATION_ID = q.ORGANIZATION_ID
AND q.LANGUAGE = 'US'
AND c.INVENTORY_ITEM_ID = r.inv_id(+)
AND NVL(c.FULFILL_ORG_ID,-1) = NVL(s.SHIPFROM_ORGID,-1))  